### ISSUE TITLE
Development Mode in browser throws error from fresh source code.

### ISSUE THREAD

**Issue by Lalit64** [27px/Remote-File-Manager#10]
Hi, @27px I have downloaded the source code of this project and didn't edit anything besides installing the dependencies, but still I get this error: 

Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at http://localhost:4500/fs/local/dir-contents/. (Reason: CORS header ‘Access-Control-Allow-Origin’ does not match ‘http://localhost’).

**Comment by 27px** [comment]
Hi, Thanks for pointing out the issue, this happened in a recent commit, Fixed it.
