### ISSUE TITLE
Remote?

### ISSUE THREAD

**Issue by barbequesauce** [27px/Remote-File-Manager#12]
Any ideas how to allow usage from a remote system, instead of only localhost?

**Comment by 27px** [comment]
Left side pannel, add ssh configuration

**Comment by barbequesauce** [comment]
Sorry, not sure I was clear - I want to run it on a headless server and use a remote browser to access the page...

**Comment by 27px** [comment]
You need to tweak some code and remove the `electron` dependency to pack node app as exe.

Option 1: No need to install on server, run the express server from local and connect to ssh, start ui on local open in browser

Option 2: run main server and ui server on remote and use remote's ip and port to access it from local.

check readme for more details

**Comment by barbequesauce** [comment]
Got it - that makes sense, didnt think of it that way - thanks!
